# Generated by Django 4.1.3 on 2022-11-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoveLetter',
            fields=[
                ('player1', models.CharField(max_length=255)),
                ('player2', models.CharField(max_length=255)),
                ('player3', models.CharField(max_length=255)),
                ('player4', models.CharField(max_length=255)),
                ('game_nr', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_nr', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(max_length=255)),
                ('game_name', models.CharField(max_length=255)),
                ('nr_players', models.IntegerField(null=True)),
                ('game_nr', models.CharField(max_length=255)),
            ],
        ),
    ]
