# Generated by Django 4.1.3 on 2022-11-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loveletter',
            name='miss_pl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loveletter',
            name='nr_players',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loveletter',
            name='state',
            field=models.CharField(default='browsing', max_length=255),
            preserve_default=False,
        ),
    ]
