# Generated by Django 4.1.3 on 2022-11-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_loveletter_miss_pl_loveletter_nr_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loveletter',
            name='nr_players',
            field=models.CharField(max_length=255),
        ),
    ]
