# Generated by Django 4.1.3 on 2022-11-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_loveletter_nr_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loveletter',
            name='nr_players',
            field=models.IntegerField(),
        ),
    ]
