from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('loveletter/', views.loveletter, name='loveletter'),
    path('loveletter/instructions/', views.loveletter_instructions, name='instructions'),
    path('loveletter/get_nr_players/', views.get_nr_players, name='get_nr_players'),
    path('loveletter/get_players/', views.get_players_loveletter, name='get_players'),
    path('loveletter/waiting/', views.waiting_loveletter, name='waiting'),
    path('loveletter/playing/', views.play_loveletter, name='playing'),
    path('loveletter/checking_pl', views.checking_pl, name='checking_pl'),
    path('loveletter/playing/draw_card', views.draw_card, name='draw_card'),
    path('loveletter/playing/discard_card', views.discard_card, name='discard_card'),
    path('loveletter/playing/end_turn', views.end_turn, name='end_turn'),
    path('loveletter/playing/get_discarded', views.update_discarded, name='get_discarded'),
    path('loveletter/playing/protected_players', views.protected_players, name='protected_players'),
    path('loveletter/playing/get_curr', views.curr_pl, name='get_curr'),
    path('loveletter/playing/round_over', views.round_over, name='round_over'),
    path('loveletter/playing/check_tokens', views.check_tokens, name='check_tokens'),
    path('loveletter/playing/round_winner', views.round_winner, name='round_winner'),
    path('loveletter/playing/guard', views.guard, name='guard'),
    path('loveletter/playing/priest', views.priest, name='priest'),
    path('loveletter/playing/baron', views.baron, name='baron'),
    path('loveletter/playing/handmaid', views.handmaid, name='handmaid'),
    path('loveletter/playing/prince', views.prince, name='prince'),
    path('loveletter/playing/king', views.king, name='king'),
    path('loveletter/playing/princess', views.princess, name='princess'),
    path('games_table/', views.game_table, name='games_table'),
]
